// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2yd3c_Yo7Yuppq-H9INH55UhmKtRk0p0',
    appId: '1:338298446122:web:e9772e6b14df711d26be53',
    messagingSenderId: '338298446122',
    projectId: 'knowbre-database',
    authDomain: 'knowbre-database.firebaseapp.com',
    storageBucket: 'knowbre-database.appspot.com',
    measurementId: 'G-C6QV29Q6GK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbcfHqXowiPu3AC8fmhh1zficALQG_v8o',
    appId: '1:338298446122:android:1c9e4bde50b521bb26be53',
    messagingSenderId: '338298446122',
    projectId: 'knowbre-database',
    storageBucket: 'knowbre-database.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp5bZs1XailFxhLeC1yGc0Z4COjFsjRq4',
    appId: '1:338298446122:ios:7c6d966d017e8fb126be53',
    messagingSenderId: '338298446122',
    projectId: 'knowbre-database',
    storageBucket: 'knowbre-database.appspot.com',
    iosClientId: '338298446122-hh37143oop57irdmi990gel7fp9ftcsc.apps.googleusercontent.com',
    iosBundleId: 'com.example.knowbre',
  );
}
